NVlabs/FPSci

docs/userConfigReadme.md
source/App.cpp
source/App.h
source/ConfigFiles.h

These changes add support for changing mouse sensitivity when in scoped mode. There are 2 mechanisms to do this:
1.  By default the mouse sensitivity is scaled by the ratio of the (horizontal) scope field of view and the "normal" horizontal field of view. This results in a lower sensitivity when the scope field of view is reduced beyond the "normal" field of view.
2. The use can override the behavior above by specifying the `scopeTurnScale` in the `userconfig.Any` file. When this `Vector2` is not 0 length (i.e. not equal to `Vector2(0,0)`) the turn scale here applies (directly) when in scoped mode. Note that this compounds with the session config and player config `turnScale`s.

Mouse sensitivity change when scoped

---

docs/general_config.md
source/ConfigFiles.h
source/Logger.cpp
source/Logger.h
source/Session.cpp

This pull request merges in changes affiliated with allowing the experiment designer to add a list of (self-referencing) parameter names from the config to write to the output database's `Sessions` table.

Add Parameter Logging for Sessions

---

docs/experimentConfigReadme.md
docs/weaponConfigReadme.md
source/App.cpp
source/App.h
source/ConfigFiles.h
source/GuiElements.cpp
source/TargetEntity.cpp
source/TargetEntity.h
source/Weapon.cpp
source/Weapon.h

This branch includes development of additional controls for rendered "bullets" and explosions (aka target destroy decals). This comes from a request from @joohwankimNV suggesting issues that are arising from new use cases.
Things to Do Include
---
* Bullets
* Size control
* Start point/offset control
* _Color control_
* Explosions
* Tie explosion time to simulation time (`sdt` approach)
* Allow user customization of "destroy decal" (size/texture/display time) _on a per-target basis_

Improvements for bullet/explosion parametric control

---

source/ConfigFiles.h

Currently an experiment designer can specify two different targets with the same `id` field value in the `experimentconfig.Any` file.
This was described in Issue #109. This branch fixes this problem by raising an exception at `experimentconfig.Any` load time if any two specified targets share a common `id`.

Don't allow the same Target ID to be entered multiple times

---

source/App.cpp
source/App.h
source/PlayerEntity.cpp
source/PlayerEntity.h

This is a branch to finalize changes around mouse sensitivity in FPSci. In summary once we merge this branch we should have a good understanding of how mouse sensitivity works in FPSci and no longer require "fudge factors" to get a correct sensitivity value from DPI and cm/360 sensitivity.
This issues originates with Issue #113 (calling the scene `onSimulation()` twice) and shed light on multiple hard coded values that didn't need to be in the application.
Merging this request closes #120.

Mouse sensitivity update

---

source/App.cpp

This adds a fix for a duplicated (incorrect) calculation from `App::updateSession()` with a call to `App::updateMouseSensitivity()`.

Replace duplicate computation w/ updateMouseSensitivity()

---

source/App.cpp
source/App.h
source/ConfigFiles.h

This branch splits the `SystemConfig` structure, previously used as an `inout` file into it's 2 constituent parts:
* System hardware configuration input (i.e. configuration for the LDAT-R logger interface)
* System hardware description output (CPU, GPU, RAM, Display Info)
Currently the system hardware info is (only) written to `log.txt` and duplicates some of the native information provided by G3D (see more about this in issue #128). We could instead/also:
* Write the system info to the output database
* Create a new output text/CSV file that only contains our (formatted) system info
* Use this information for automatic validation that the system meets some (specificed) min spec for certain experiments
Currently the `SystemInfo` class has been implemented (in `configFiles.h`) to get/store …

Split SystemConfig into Input/Config Files and HW Information/Output Files

---

source/GuiElements.h

This branch creates a copy of the `MenuConfig` within the `UserMenu` class as opposed to using a reference as a member.
We may also consider moving away from the use of references for the `UserTable `and `UserStatusTable` in the future (but not part of this pull request).
Merging this pull request closes #138.

MenuConfig as reference instead of copy in UserMenu

---

docs/experimentConfigReadme.md
docs/general_config.md
docs/getting_started.md
docs/startupConfigReadme.md
docs/systemConfigReadme.md
docs/userConfigReadme.md
docs/userStatusReadme.md
docs/weaponConfigReadme.md

Updating some issues found in the documentation, these include:
* Static HUD documented under the wrong section of general config
* Broken link to weapon configuration from the general config
* Removing links to no longer present config files
* Updating header/section links to get them working in Github
Only markdown/documentation files should change as part of this branch/pull request.
This branch can remain present after merging this pull request to give us a place to address future documentation problems not discovered in affiliation with a specific feature/pull request.

Documentation fixes

---

source/App.cpp
source/App.h
source/GuiElements.cpp
source/GuiElements.h

This fix moves to "recreation" of the `UserMenu` rather than attempting to "update it in place" when a new user/session is selected. This solves a set of issues introduced by the user menu refactor in commit [2617d1](https://github.com/NVlabs/abstract-fps/commit/2617d1d6472e3ad800489aa4ac2932529e7feeab).
The user menu is now recreated on user/session update and uses semaphore-based message passing to avoiding doing this recreation directly in the callback of the button press (from within the window). This also adds an App-specific `App::onAfterEvents()` to the set of `GApp` functions implemented by the FPSci app.
Merging this request closes #141

Fix for "Select Session" bug

---

source/ConfigFiles.h
source/GuiElements.cpp

This PR addresses an issue wherein the lack of calling `c_str()` on some of our default `G3D:String` objects results in odd print/display behavior for the contents of these strings.
This was not an issue when loading from Any, but seemed to be an issue when initializing the strings directly from within C++.
Merging this pull request closes #154.

Error printing/displaying user (and other) info on first run

---

docs/general_config.md
source/ConfigFiles.h
source/FPSciApp.cpp
source/FPSciApp.h
source/Session.cpp

This branch implements flags for control over whether:
* The user menu is open at app startup (`showMenuOnStartup`)
* The user menu is opened automatically at the end of each session (`showMenuBetweenSessions`)
Merging this pull request closes #151

Automatic session progression

---

source/FPSciApp.cpp
source/FPSciApp.h

Center dialog boxes used to ask users questions following a session. Consider adding support for optional opening of the user menu when questions are asked as well.
Merging this PR closes #158.

Center the question dialog(s) on top of user menu

---

source/GuiElements.h

Quick fix to solve for starting the application with the user config's `currentUser` set to a user who has all sessions completed.
Merging this PR closes #157.

Fix start with all of current user's sessions complete

---

source/ConfigFiles.h
source/GuiElements.cpp

This branch implements two changes around the `UserTable` structure and it's interaction with the in-app user menu.
1. The user config file is now saved in accordance with the `userConfigPath` provided in the startup config Any file and it's corresponding `StartupConfig::userConfig()` accessor.
2. The user config file's `currentUser` field is now updated/saved whenever the user presses the "Select User" button within the GUI.
Merging this PR closes #160.

Update user config on user change in application

---

docs/experimentConfigReadme.md
source/ConfigFiles.h
source/Session.cpp

This branch adds support for an (independent) session and experiment-level `closeOnComplete` flag. 
*The experiment-level `closeOnComplete` flag closes the application when _all sessions_ within the experiment are complete. This also closes the application when opened with no sessions remaining.
*The session-level `closeOnComplete` flag closes the application when the particular session it is specified on is complete. This allows a way for experiment designers to regulate the flow of users through various sessions.
Merging this PR closes #166.

Add automatic closing of app on experiment/session end

---

docs/general_config.md
source/ConfigFiles.h
source/Session.cpp
source/Session.h

This branch implements the `showRefTarget` flag for session/experiment level configuration that allows the user to specify that the reference target (not) be drawn between trials within the session.
Merging this PR closes #164.

Experiment designer control of whether to show reference target

---

source/ConfigFiles.h

Previously `closeOnComplete` and `blockCount` were always serialized to a session, regardless of whether these fields had their default values. This branch makes serializing these two fields to the experiment conditional on them having non-default values (like most FPSci config structures).

Only serialize non-default session-specific config parameters

---

docs/general_config.md
source/ConfigFiles.h
source/Session.cpp

This branch adds a `scoreboardRequireClick` parameter to the timing configuration that allows the experiment designer to require a left mouse click event to progress from the scoreboard state (in addition to the `scoreboardDuration` timing having expired.
Merging this request closes #179.

Add requirement for click in addition to scoreboardDuration parameter

---

source/FPSciApp.cpp

This fixed a bug @joohwankimNV noticed in releases v20.06.02 and v20.06.03 where the scene editor window would show on startup regardless of the `developerMode` setting in the startup config.

Scene window shows based on developerMode setting

---

.gitignore
docs/startupConfigReadme.md
source/ConfigFiles.h
source/FPSciApp.cpp
source/Logger.cpp

This branch adds support for specifying a `resultsDirPath` in the startup config file to allow the experiment designer to redirect the results directory wherever they would like. It also adds support for creating an arbitrarily named results directory if one does not already exist.
Merging this PR closes #190

Configure results directory path from startup config

---

source/Session.cpp

This branch removes the requirement on the session config's `description` being `"training"` in order to print per trial feedback. Sessions that should not include per trial feedback can remove feedback messages by setting the `trialSuccessFeedback` and `trialFailureFeedback` to empty strings.
Alternatively (if desired) we can make the default per trial feedback strings empty.
Merging this PR closes #185.

Per trial feedback unconditional of session description

---

docs/general_config.md
source/ConfigFiles.h
source/Session.h

This branch adds support for a `CommandSpec` which allows the experiment designer to specify `foreground` and `blocking` flags for any given command.
This slightly modifies the syntax for specifying command arrays in the experiment config file from:
```
commandsOnSessionEnd = [ "testcommand.exe" ];
```
to
```
commandsOnSessionEnd = [ { command = "testcommand.exe" } ];
```
This restructure allows the `foreground` and `blocking` parameters to be specified along with the `command`. For example, to open a foreground browser with a web page at the end of a session, the designer can specify:
```
commandsOnSessionEnd = [ { command = "cmd /c start [webpage URL]", foreground = true } ];
```

Foreground and blocking commands

---

docs/general_config.md
source/ConfigFiles.h
source/FPSciApp.cpp
source/Session.cpp
source/Session.h
source/TargetEntity.h
tests/FPSciTests.cpp

This branch adds support for showing a user "previews" of real targets while the reference target is being drawn. The feature is enabled using the `showPreviewTargetsWithReference` flag in a session/experiment config.
The preview targets can be delineated from "real" targets using their color (settable with the `previewTargetColor` parameter in the session/experiment config).
Merging this PR closes #187.

Target previews

---

data-files/test/startupconfig.Any
docs/startupConfigReadme.md
source/ConfigFiles.h
source/FPSciApp.cpp
source/FPSciApp.h

This branch adds support for specifying the user status as well as the latency logger config (via their full file paths) in the startup config file.
Merging this PR closes #194.

Add support for all config paths in startup config

---

source/GuiElements.cpp
source/Session.cpp

Stops 2 crashes.
First is a crash when starting with no valid sessions for the selected user.
The second is a crash when switching to a user with no valid sessions. Unfortunately, this allows running the session that was selected for the user that still had valid sessions before switching to the user with no remaining sessions. It may be worth fixing this bug before merging.

Prevents crash with no valid sessions

---

docs/general_config.md
source/ConfigFiles.h
source/Session.cpp

This branch adds support for a `clickToStart` parameter (to be renamed?) that makes the first click (previously required to start a session) optional.

Add clickToStart experiment config parameter

---

FPSci.lib.vcxproj
FPSci.lib.vcxproj.filters
docs/general_config.md
docs/systemConfigReadme.md
source/ConfigFiles.h
source/FPSciApp.cpp
source/FPSciApp.h
source/Session.cpp
source/Session.h

This branch removes the system config (renamed to `LatencyLoggerConfig` in code) in favor of uniting these parameters with the experiment config file. This has become the de-facto standard anyway as other loggers are now using commands specified in the `experimentconfig.Any` file rather than using the system config as intended.
It also adds support for replace-able substrings in commands, notably `%loggerComPort` and `%loggerSyncComPort` which now come from their affiliated input fields in the experiment config file.
Merging this PR closes #197.

Refactor system/latency logger config

---

source/FPSciApp.cpp

This fixes a bug wherein "uncrouch" (releasing the crouch control button) was not detected.

Fix for crouch "latching" bug

---

.gitignore
vs/FPSci.test.vcxproj

This is a fix to get the tests looking for the `packages` directory inside of the `vs` directory where it gets placed after the changes from #210 
This fix is only needed for the tests to work correctly.
This is an updated version of #212 since that pull request wouldn't let us merge it (thanks github).

Test `packages` path in `vs`

---

.gitignore

This accidentally got missed (because github fail) in #213

Removed unused ignore `x64`

---

source/ConfigFiles.h
source/FPSciApp.cpp
source/FPSciApp.h
source/Session.cpp
source/TargetEntity.h

This branch re-uses target materials (rather than creating new ones in `TargetEntity::setColor()` for activating targets). This should remove "activation artifacts" that might be caused by lengthy material allocation.
The concept is that the pre-created materials in the `FPSciApp::m_materials` array can be used to "activate" targets rather than creating a new one at runtime.
`TargetEntity::setColor()` is still used for spawning targets as this has not been reported as an issue in the past/is an easy way to create the preview material from within the `TargetEntity`.

Split/reuse updateTargetColor() for preview targets

---

data-files/test/experimentconfig.Any
data-files/test/userstatus.Any
source/FPSciApp.cpp
source/FPSciApp.h
source/Session.cpp
source/Session.h
source/TargetEntity.h
source/WaypointManager.cpp
tests/FPSciTests.cpp
tests/FPSciTests.h

This branch changes the `TARGET_MODEL_ARRAY_SCALING` macro in code to extend the range of the model scaling at some limited cost to scale granularity.
FPSci implements model sizing by:
1. Sizing the model to 1m with a "default" scale factor
2. Applying an additional logarithmic scale following: 
```scale = (1 + TARGET_MODEL_ARRAY_SCALING) ^ (i - TARGET_MODEL_ARRAY_OFFSET)```
where `i` is the index within the array (in the range `[0, Target array length - 1]`)
The "fix" here is to keep the target model array the same size, but increase the `TARGET_MODEL_ARRAY_SCALING` (slightly) to increase the range of target sizes that can be created from within the application. This allows a wider range of target scales to be represented (at lower granularity).
Specifically the request from …

Extend model scaling range w/ scale factor

---

docs/developermode.md
docs/keymap.md
source/ConfigFiles.h
source/FPSciApp.cpp
source/FPSciApp.h
source/GuiElements.h

This branch adds support for a new `reloadConfigs` key within the key map. When `developerMode=true` in the startup config, this allows developers to reload configs from within the application without restarting. By default this key is set to `F5` to coincide with the generic reload offered by G3D.
Merging this PR closes #127

Allow developers to reload their configs from disk while running

---

docs/general_config.md
source/FPSciApp.cpp
source/FPSciApp.h
source/Session.cpp
source/Session.h

This branch adds support for a `%dbFilename` sub-string that can be used in commands to reference the db file currently being written to. The substring does not include the `.db` extension so users can refer to other file types by this name as well.
This should be useful in getting correspondence between logs produced by FPSci and logs output from other logging utilities where the output filename can be specified within the command that calls the logger.

dbFilename command substring support

---

source/main.cpp
tests/main.cpp

This pull request taps into the newly exposed G3D ability to control the DSP buffer size, which affects the audio latency. At the moment, it's unclear what cost these changes have, so I'm opening this pull request up with the intent to test it.
The smaller buffer sizes proposed to reduce latency, but at the cost of increase CPU utilization, which I haven't yet characterized. We need to examine how much that cost is to decide whether it's worth paying, or if we want a less (or more) aggressive setting.

Lower audio latency (requires G3D r7012 or newer)

---

docs/general_config.md
source/ConfigFiles.h
source/FPSciApp.cpp

This branch adds support for additional feedback formatting, namely:
- Controllable text (outline) color
- Controllable font size
- Controllable/optional back plate (w/ alpha) to improve readability 
Merging this closes #231

Feedback message color

---

docs/general_config.md
docs/userConfigReadme.md
source/ConfigFiles.h
source/FPSciApp.cpp
source/GuiElements.cpp
source/GuiElements.h

This branch adds support for adding new users from within the application. As it a result it also adds:
- A user configuration flag to require unique user IDs (`requireUnique` in the user config)
- A user menu field/button for entering/adding new user IDs and a field providing feedback on empty/duplicate user IDs
- Support for automatically switching to the added user
Once new users are created the user can be directed to setup their mouse sensitivity and/or reticle (depending on what is allowed for the experiment) from the normal user menu.

Add new users

---

source/FPSciApp.cpp

This branch fixes a bug wherein propagated (non-hitscanned) projectiles could destroy "preview" targets prior to the reference target being hit.
Merging this PR closes #246.

Use hittable targets for projectile simulation

---

docs/userConfigReadme.md
source/ConfigFiles.h
source/GuiElements.cpp

This branch adds support for a `defaultUser` field in the user configuration file, primarily intended to setup the default values for new users added from the in-app user menu. This acts as a fix for the "bug" of newly created users inheriting some default `UserConfig` values/values from other users in the configuration.

Add support for a defaultUser to user config

---

docs/general_config.md
source/ConfigFiles.h
source/GuiElements.cpp

This branch adds an `allowSessionChange` control flag to disable users from updating the session from the user menu.

Add allowSessionChange control flag

---

docs/experimentConfigReadme.md
source/ConfigFiles.h

Previously setting a trial's `count` field to a value <= 0 caused a session management glitch within the application. This branch adds support for documenting that the `count` should be an integer >0 and adds an exception to catch this case, preventing the app from entering the session logic glitch.

Add check/documentation for trial count > 0

---

docs/weaponConfigReadme.md
source/ConfigFiles.h
source/FPSciApp.cpp
source/GuiElements.cpp
source/GuiElements.h
source/Weapon.cpp
source/Weapon.h

This branch adds support for bullet spread via the `fireSpread` configuration parameter in the weapon configuration. By default this spread value is set to 0, maintaining the purely deterministic shot behavior previously used in FPSci.
Currently the fire "spread" is shot-to-shot and uniformly distributed/sized in azimuth/elevation with no effects of things like the time since the last shot was made. If we'd like we can extend this to include:
- Impact of time since the last shot
- Asymmetric azimuth and elevation spread
- Support for multiple projectiles in a single shot
This branch does not currently support changing the damage of the weapon based on shot spread (i.e. distance from central aim direction) in any way.

Add (optional) bullet spread

---

.gitignore
data-files/scene/Test_Cornell_Box.Scene.Any
data-files/test/experimentconfig.Any
docs/scene.md
source/FPSciApp.cpp
source/FPSciApp.h
tests/FPSciTests.cpp
vs/FPSci.test.vcxproj
vs/FPSci.test.vcxproj.filters

This branch fixes a bug from `FPSciApp::onAfterLoadScene()` wherein the `playerCamera` was being inserted into the scene after the scene is loaded (which already inserts the camera). This exception only showed up when running the application in the `Debug` configuration, and was ignore-able, but caused confusion for some developers.
Merging this PR closes #264.

Remove duplicate insert of playerCamera into scene

---

docs/developermode.md
docs/startupConfigReadme.md
source/ConfigFiles.h
source/FPSciApp.cpp
source/FPSciApp.h
source/GuiElements.cpp
source/GuiElements.h

This branch adds support for selecting the experiment from an `experimentList` when in developer mode.
The approach is a bit complicated, but should make things easier for users. The only config changes are in the startup config file, which now supports 2 new fields (and drops support for "direct" configuration file specification):
- A `defaultExperiment` which sets up the files to use as defaults for experiment(s) if none are provided, and specifies the only experiment if no `experimentList` is provided
- An `experimentList` which provides a list of (named) experiments as deviations from the `defaultExperiment` provided above
The `defaultExperiment` and `experimentList` entries contain the same file fields that used to exist at the top level of the startup config, namely:
- …

Experiment selection

---

source/FPSciApp.cpp
source/FPSciApp.h
source/Session.cpp
source/Weapon.cpp
source/Weapon.h
tests/FPSciTests.cpp

In #269 the new tests don't yet pass, and it made sense to do a rather large restructuring of the code around weapon firing. This pull request moves the weapon firing into `onSimulation` instead of `onUserInput` so that it can be decoupled.
In its current state, this partly works, but it still doesn't pass all the tests, and there's likely some additional issues still present. I'm creating another pull request into the main PR in case this path ends up being unproductive and we decide to do something else.

Moves weapon firing to onSimulation

---

source/Dialogs.h
source/FPSciApp.cpp
source/FPSciApp.h
source/GuiElements.cpp

This branch contains improvements for displayed questions (specifically improvements for fullscreen questions without the cursor shown) including:
1. Removing the "submit" and "clear" buttons when the cursor isn't shown for questions (i.e. key-based responses)
2. Vertical and horizontal centering of question prompt/options
3. Disabling first person manipulator camera view control when displaying questions without a cursor

Question improvements

---

source/ConfigFiles.h
source/main.cpp

This branch introduces a `StartupConfig::load()` static method that handles checking for a valid startup config, creating one if not available, then returning the resulting object. This solves the issue of an exception at startup when running without a valid `startupconfig.Any` file in the `data-files` directory (i.e. when a new `startupconfig.Any` is created).
Merging this PR closes #277.

Startup config loading

---

docs/experimentConfigReadme.md
docs/general_config.md
docs/weaponConfigReadme.md
source/FPSciApp.cpp
source/Weapon.cpp
source/Weapon.h

Fixes an issue where an empty string value for `sceneHitSound` in the experiment/session config resulted in a null pointer exception at runtime.

Null check for scene hit sound

---

source/UserConfig.cpp
source/UserConfig.h

This branch adds support for serializing the `defaultUser` of the user config back out when a user is updated/created.
Merging this PR closes #291.

Default user to userconfig.Any

---

source/TargetEntity.h

This branch adds a fix for player-space jumping targets not respawning with newly randomized motion parameters.
Merging this PR closes #271.

Fix for jumping target respawn behavior

---

source/FPSciApp.cpp
source/Session.cpp

Quick null check addition to prevent crash in `Session::processResponse()`
Merging this PR closes #294.

Logger null check in Session::processResponse()

---

docs/startupConfigReadme.md
source/ExperimentConfig.cpp
source/ExperimentConfig.h
source/FPSciApp.cpp
source/StartupConfig.cpp
source/StartupConfig.h

This branch adds support for an `ExperimentConfig::validate()` routine that is called (optionally) on `ExperimentConfig::load()`. Specifically this validate routine checks that the set of target ids used in session `TrialCount` objects match the global list of targets specified in the experiment config `targets` array.
Merging this PR closes #289.

Experiment config validation

---

docs/weaponConfigReadme.md
source/Session.cpp
source/Weapon.cpp
source/Weapon.h

This branch adds:
- A quick fix for the `Weapon::clearDecals()` call that removes decals from the scene
- A new `clearTrialMissDecals` weapon config flag (defaults to `true`) that allows experiment designers to choose whether miss decals are removed at the start of a new trial
- A new `missDecalTimeoutS` weapon config parameter (default to `-1` for no timeout) that allows experiment designers to set a (simulation time-based) timeout for miss decals

Clearing miss decals on new sessions/trials

---

docs/weaponConfigReadme.md
source/Weapon.cpp
source/Weapon.h

This branch adds support for a weapon config `loopFireSound` parameter that can be set to `true` (default is `false`) to enable looped audio playback for automatic, but not continuously firing, weapons. Continuously firing weapons (i.e. lasers) have always used looped audio in FPSci.

Add loopFireSound parameter to weapon

---

source/FPSciApp.cpp
source/FPSciApp.h

The G3D `LAUNCH_SHADER` macro has a `static` variable inside, assuming the same shader will be provided every time that macro is used. This PR switches to the `LAUNCH_SHADER_PTR` macro that allows us to control shader loading and caching explicitly.
Fixes a bug where sessions with different custom shaders would always use whichever shader was loaded first.

Cache session shaders manually to work around LAUNCH_SHADER assumption

---

docs/general_config.md
source/FpsConfig.h

This branch sets the configuration default (unspecified values) of `crouchHeight` to `playerHeight` (i.e. no crouch) and `jumpVelocity` to 0 (i.e. no jump) so that these do not need to be explicitly disabled in future experiments that don't desire player motion.
This mirrors the default `moveRate` value of 0 (i.e. no motion by default).

Disable crouch/jump as default (if unspecified)

---

docs/general_config.md
source/FPSciApp.cpp
source/FpsConfig.cpp
source/FpsConfig.h

This branch adds support for a `randomOrder` flag specified per question that allows randomized shuffling of `MultipleChoice` and `Rating` question options at presentation time. This is intended to reduce bias in presenting options in the same order repeatedly.

Add support for question response order randomization

---

source/Session.cpp

This branch adds support for an issue in which destination targets are not spawned at the correct location initially. The primary intent of this fix is allowing a simple world-space static target to be created using a single-point destinations array (as opposed to a world-space parametrized target with a zero width spawn bounding box):
```
targets = [
{
id = "point"; destSpace = "world";     
destinations = [{ t: 0, xyz: Point3(38.75, -1.3, 0.7)}];
}
...
];
```
It's reasonable to assume this bug also impacts destination-based targets with more than a single destination that rely on the target to spawn at their first position rather than (0,0,0) initially
Merging this PR closes #297

Fix for spawning destination targets at their first destination

---

data-files/test/experimentconfig.Any

The `spawnBounds` provided in the `data-files/test/experimentconfig.Any` were causing errors on debug startup (specifically in developer mode). This branch corrects the bounds so that the debug errors no longer occur.

Fix spawn bounds AABox to remove debug error

---

docs/general_config.md
docs/resultsFiles.md
source/ExperimentConfig.cpp
source/FpsConfig.cpp
source/FpsConfig.h
source/Logger.cpp
source/Session.cpp
source/Session.h

This branch adds support for random-in-range `pretrialDuration`. This does not break previous configs by allowing experiment designers to specify _either_ a scalar value or a 2-array of values for randomization in range. This array is expected to be formatted `[min value, max value]`.
Exceptions are raised when the specified array is undersize (of length 0 or 1), and warnings are printed to the log when oversized (of length >2).
Merging this PR closes #309.

Add support for random in range `pretrialDuration`

---

docs/general_config.md
source/FpsConfig.cpp
source/FpsConfig.h
source/Session.cpp
source/Weapon.cpp
source/Weapon.h

This branch adds a `showReferenceTargetMissDecals` parameter to allow experiment designers to specify whether miss decals should be displayed when firing at the reference target. This parameter defaults to `true` to maintain historical behavior. To disable it, add:
```
showReferenceTargetMissDecals = false;
```
to your experiment config.

Add `showReferenceTargetMissDecals` parameter

---

docs/general_config.md
source/FpsConfig.cpp
source/FpsConfig.h
source/Session.cpp

This branch adds support for a `clearMissDecalsWithReference` parameter that allows the experiment designer to specify whether or not miss decals created while firing at the reference target are cleared when the trial task begins. The parameter defaults to `false` to preserve historical behavior. To enable, add:
```
clearMissDecalsWithReference = true;
```
to your experiment config.

Add `clearMissDecalsWithReference` parameter

---

data-files/test/experimentconfig.Any

This pull request disables all sounds that should play in the current set of test cases. This should make running the tests a bit more bearable since they'll be quiet.
I did intentionally leave a sound on for the target that shouldn't be destroyed in case it does it get destroyed since sound when the test case fails should be fine.

Turn off sounds for test experiment

---

docs/AnyFile.md
docs/general_config.md
source/FPSciApp.cpp
source/FpsConfig.cpp
source/FpsConfig.h
source/Session.cpp
source/Session.h

This PR adds support for specifying frame rate variability through one of the following approaches. This PR adds two render parameters, `frameTimeArray` and `randomFrameTime`, both of which are ignored if `frameTimeArray` is empty, which is the default.
* Specify a frame time sequence to follow by placing that sequence in `frameTimeArray` and setting `randomFrameTime = false`.
* Specify a frame time distribution to choose from randomly by placing the list of frame times in `frameTimeArray` and setting `randomFrameTime = true`.

Support for programmable variable frame rate

---

docs/general_config.md
source/FPSciApp.cpp
source/FPSciApp.h
source/FpsConfig.cpp
source/FpsConfig.h

This branch adds support for a `referenceTargetHitSound` config parameter (along with a `referenceTargetHitSoundVol` parameter for volume control) to the audio configuration within the FPSci general configuration.
To demonstrate you can add:
```
referenceTargetHitSound = "sound/fpsci_destroy_150ms.wav";
```
to (the top of/any session in) your experiment configuration file. This should automatically play the specified destroy sound for the reference target. Currently the behavior in this branch defaults to no audio for the reference target, but we can change this default value if we'd like.

Add `referenceTargetHitSound` to audio config

---

source/FPSciApp.cpp
source/FPSciGraphics.cpp
source/TargetEntity.h
source/WaypointManager.cpp
source/WaypointManager.h

This branch moves to null checking `waypointManager` rather than using the `waypointEditorMode` parameter from the startup config. The `waypointManager` is only created when `waypointEditorMode` = `true` _and_ `developerMode` = `true` in the startup config.
This prevents an exception from setting `waypointEditorMode` = `true` with `developerMode` = `false` and simplifies our code.
Merging this PR closes #320.

Use waypointManager null check instead of `waypointEditorMode` parameter

---

source/TargetEntity.cpp

This branch adds a fix for waypoint target motion that corrects how targets interpolate between (more) distant waypoints.
Specifically it corrects some issues with the way the (linear) interpolation between waypoints worked previously and adds more descriptive variable names/comments to help indicate what is happening.
This branch also makes a minor change to the conditions under which the target's `m_lastChangeTime` is set.

Fix for waypoint target motion

---

scripts/package/fpsci_packager_generator.py

Improves the FPSci packager generator to only detect `/game/` paths to avoid accidentally noticing paths that happened to have "game" as a part of a folder or file name.

Improve handling of G3D paths in packager

---

scripts/event logger/software/event_logger.py

This branch adds a fix for initializing the `lastADCTime` variable at the top of the file to prevent an exception that prevents the `event_logger.py` script from running.

Initialize lastADCTime to fix error

---

source/FPSciApp.cpp
source/FPSciApp.h
source/FPSciGraphics.cpp
source/GuiElements.cpp
source/GuiElements.h

This branch removes `emergencyTurbo` which was causing issues with controlling AA, bloom, and AO (from the scene) when not set.

Remove emergencyTurbo mode

---

data-files/scene/Simple_Hallway.Scene.Any
data-files/scene/Test_Cornell_Box.Scene.Any
data-files/test/experimentconfig.Any
docs/general_config.md
docs/scene.md
source/FPSciApp.cpp
source/FPSciApp.h
source/PlayerEntity.cpp
source/PlayerEntity.h
tests/FPSciTests.cpp

This branch cleans up scene-level specification of `PlayerEntity` heading using the `frame` of the `VisibleEntity` as opposed to a purpose-built Any field. It also attempts to fully unify the player camera and player heading from when the `PlayerEntity` is loaded from Any.
Merging this PR closes #332

Scene heading

---

docs/general_config.md
source/Dialogs.h
source/FPSciApp.cpp
source/FpsConfig.cpp
source/FpsConfig.h

This branch improves specification of questions to clarify some issues and improve control of presentation of questions. Changes include:
1. Automatically default `randomOrder` to false when displaying questions with `type` of `Rating`
2. Add a `optionsPerRow` field that defaults to `3` (maintains old behavior) but allows custom layout of questions with `type` of `MultipleChoice`
3. Warn the user (via log.txt) that when a question with `type` of `Rating` is provided the `optionsPerRow` will be ignored in favor of displaying all options on one row (use `MultipleChoice` questions for controlled layout).
4. Allows font size setting for questions.
Merging this PR closes #344

Improve Question Specification

---

docs/general_config.md
source/FPSciApp.cpp

This branch fixes a bug when using `randomOrder` questions with `optionKeys` specified. Previously logged responses were potentially incorrect in this configuration. Now the mapping of `options` to `optionKeys` does not change when `randomOrder = true` is specified in config. Only the presented order of options is changed (the key binds remain the same).
Merging this PR closes #356.

Random order question key bind fix

---

docs/experimentConfigReadme.md
docs/general_config.md
source/FPSciApp.cpp
source/FpsConfig.cpp
source/FpsConfig.h
source/Session.cpp
source/TargetEntity.cpp
source/TargetEntity.h

This branch reverts a hard-coded glossiness assumption that was previously used in FPSci. Targets and session/experiment level config can now specify their `gloss` and `targetGloss` respectively with per-target gloss overriding the global settings (similar to target color configuration).

Add specification of target glossiness to configuration

---

source/Session.cpp
source/Session.h
source/TargetEntity.cpp
source/WaypointManager.cpp

This branch cleans up a sloppy implementation of target offsets that was not thoroughly tested.
It corrects offset values to 0 for world-space targets (as expected) and leaves the existing offsets for player-space destination targets. It should also correct for player-space targets loaded via the waypoint manager at the current player position.
Merging this PR closes #352.

Destination target offset fix

---

source/FPSciApp.cpp
source/Session.cpp

This branch adds a `FilePath::isLegalFilename()` check on the filename used for the results database. Previously the results could fail to write due to an illegal character in either an experiment description or a user name.
The new check should throw an exception when any invalid filename character is detected in the results filename. It is worth noting this may catch characters that technically legal but not encouraged for file naming.
Merging this PR closes #351

Check for legal results filename

---

docs/experimentConfigReadme.md
docs/general_config.md
source/FPSciApp.cpp
source/FPSciApp.h
source/FpsConfig.cpp
source/FpsConfig.h
source/TargetEntity.cpp
source/TargetEntity.h

This branch adds support for setting target emissive color (previously hard-coded to 0.7*color) using 2 different mechanisms. Targets can specify it using an `emissive` parameter or it can be specified at the experiment-level using `targetEmissive`, both of which take a `Color4` as input.
Merging this PR closes #370

Target emissive control

---

source/Session.cpp

This branch moves to using the `allSessionsCompleteFeedback` string when starting up the application with no new sessions. Previously a hard coded message of `"All sessions complete!"` was used.
Merging this PR closes #378

Use `allSessionsCompleteFeedback` at startup

---

docs/general_config.md
source/FpsConfig.cpp
source/FpsConfig.h
source/GuiElements.cpp

This branch adds a `logSessionDropDownUpdate` parameter that defaults to `False` in order to prevent logging large session lists to the `log.txt` file every time the session/menu is updated.
This parameter is slightly different than other `log[X]` parameters in that it does not control logging to the database results but rather the local log.

Add `logSessionDropDownUpdate` parameter

---

source/Session.cpp

This branch fixes an error with `closeOnComplete` that caused experiment-level specification of the parameter to not work as intended. It also removes some unused code handling no remaining sessions in a way FPSci no longer supports. This branch should return the experiment-level `closeOnComplete` parameter to its desired behavior.
Merging this PR closes #387.

Close on complete fix

---

docs/general_config.md
source/FPSciApp.cpp
source/FPSciApp.h
source/GuiElements.cpp
source/GuiElements.h

This branch adds support for a `requireUserAdd` parameter in the general configuration of FPSci. When enabled this flag requires a new user to be added via the existing user menu prior to starting an experiment on each run of FPSci. Note that if FPSci is closed an existing user will still need to create a new user with the current implementation.
The user menu is drawn differently when `requireUserAdd = true`, will always be shown at startup, and cannot be closed until a new user is added in an effort to make the requirement more self-evident. Once a new user is added the typical user menu behavior resumes (allowing experiment configured user customization).
Merging this PR closes #373

Add `requireUserAdd` parameter

---

docs/general_config.md
source/FPSciGraphics.cpp
source/FpsConfig.cpp
source/FpsConfig.h
source/Session.cpp
source/Session.h

This branch adds support for some additional scoring models for FPSci. Specifically it adds support for a `scoreModel` and `scoreMultiplier` parameter that allow more customization of scoring. Valid `scoreModel`s include `time remaining` (historical), `targets destroyed`, `shots hit`, `accuracy`, and `trial successes`.
We can add more scoring modes in the future if we would like using this model.

Add alternate scoring models

---

source/FPSciApp.cpp
source/TargetEntity.h
source/Weapon.h

This PR makes audio play when first loaded to avoid stuttering when it first needs to play.
When finished, closes #375 
With some luck may also help #275 , but it doesn't fix that yet.

Pre-play audio on first load

---

source/SystemConfig.h
source/SystemInfo.cpp
source/SystemInfo.h

This branch adds support for null checking results of `std::getenv()` calls which can be `null` when the requested values aren't set in the environment variables (as documented [here](https://en.cppreference.com/w/cpp/utility/program/getenv)).
Merging this PR closes #398.

Getenv null check

---

tests/FPSciTests.cpp

This branch resets the weapon cooldown at the start of target kill tests. Since app state isn't reset between tests the weapon cooldown was (in some cases) preventing a fire event from occurring as the weapon is still in its 0.1s cooldown.
Overall we should probably improve test infrastructure by resetting most of this state in the app prior to running each test instead of just relying on the fixture to do this. It is likely a certain sequence of tests could potentially still result in (illegitimate) failures.
Merging this PR closes #275 and closes #243.

Reset weapon cooldowns at the start of kill tests

---

source/FPSciApp.cpp

This PR sets the guard band to 0 instead of 64 like it was previously. This effectively fixes and issue that the configured FoV was 93.75% of the intended value (1920/2048) at 1080p.
I'm not sure if this is the fix we want for this issue yet.
**IMPORTANT: This breaks backwards compatibility with older experiments since the FoV setting gives different results.**

Set guard band to 0

---

source/FPSciApp.cpp

After trial-level configuration the `playerCamera` was not initialized in FPSci when loading a completed experiment. This caused null pointer exceptions when running `oneFrame()`. This branch assigns the `playerCamera` and adds null checking to avoid these exceptions while still displaying the `allSessionsCompleteFeedback` message.

Fix for crash on load w/ experiment complete

---

docs/general_config.md
source/FPSciApp.cpp
source/GuiElements.cpp
source/UserConfig.h

This branch fixes a buggy interaction between specifying reticle configuration parameters at the experiment/session/trial level and using `allowReticleChange = true` to enable the user menu reticle configuration GUI.
The app now treats specifying any reticle configuration at the experiment/session/trial level as equivalent to setting the corresponding field's `allowReticle[X]Change` parameter to `false`. Thus the only reticle parameters users are free to configure are those not specified as part of experiment configuration. 
Merging this PR closes #361

Fixes for reticle preview and `allowReticleChange`

---

source/FPSciApp.cpp

This branch fixes exceptions thrown when changing experiments using the GUI in debug mode. The fix is simply not to modify the `m_widgetManager` prior to reinitializing the application.

Don't modify widget manager prior to reinit

---

source/FPSciApp.cpp

This branch fixes an issue in the `Weapon::loadSounds()` call that was creating an exception when `audioEnable` was set to `false` in the startup config. 
Merging this branch closes #413.

Don't load weapon sounds if audio disabled

---

README.md
vs/FPSci.lib.vcxproj
vs/FPSci.test.vcxproj
vs/FPSci.test.vcxproj.filters
vs/FirstPersonScience.vcxproj
vs/packages.config

This branch updates the FPSci solution to work with visual studio 2022 (from 2019). In addition to updating the `PlatformToolset` to `v143` this branch also updates the google test package to version `1.8.1.7`.

Updates for VS 2022

---

source/Session.cpp

This fix bypasses the `referenceTarget` state of the state machine when `showReferenceTarget = false`, avoiding the issue of ignoring this configuration.
Merging this PR closes #425.

Fix for `showReferenceTarget = false`

---

source/GuiElements.cpp

This branch adds a check for whether a dialog is open prior to entering `MOUSE_FPM` mode (first-person view) in FPSci. Currently it only does this for a single path (user menu `Resume` button), but we could extend this to be the way we set the mouse mode more generally in FPSci (i.e. only change the mouse mode to `MOUSE_FPM` when neither a dialog nor the menu is present).
Merging this PR closes #417.

Check whether a dialog is present before FPM mode
