NVlabs/FPSci

- scripts/simple_path_create.py
Adding in a scripts directory and some Python for example path creation.
> Added a simple script for generating random paths to CSV output

- code/data-files/DEVexperimentconfig.Any
- code/source/App.cpp
- code/source/App.h
- code/source/ExperimentConfig.h
- code/source/ReactionExperiment.cpp
- code/source/TargetEntity.cpp
- code/source/TargetExperiment.cpp
Creating a pull request to merge this progress thus far. Still need session/trial selection and iteration logic to be added. From here on I can coordinate work and push directly.
> Merging in changes supporting experimentconfig.Any file

- code/data-files/SAMPLEexperimentconfig.Any
- code/data-files/SAMPLEuserconfig.Any
merging to master branch to apply changes made during pilot experiment.
> Pilot experiment 20190416

- source/App.cpp
- source/App.h
- source/Session.cpp
- source/Session.h
- source/TargetEntity.cpp
- source/TargetEntity.h
- source/WaypointManager.cpp
- source/WaypointManager.h
This is a branch to simplify the interface(s) used to spawn targets from the app/session. Currently this branch is a work in progress.
> Improve target spawning

- FirstPersonScience.vcxproj
- FirstPersonScience.vcxproj.filters
- source/App.cpp
- source/App.h
- source/CombatText.h
- source/Dialogs.h
- source/Logger.cpp
- source/Logger.h
- source/PythonLogger.h
- source/Session.cpp
- source/Session.h
- source/TargetEntity.h
- source/WaypointManager.h
- source/sqlHelpers.h
Does the following:
- Splits combat text into a separate header
- Renames Logger to FPSciLogger
- Renames G3Dialog to DialogBase
- Renames PyLogger.h to PythonLogger.h
- Removes unimplemented sqlHelper functions
> Various code restructuring changes

- data-files/shader/distort.pix
- source/App.cpp
Setup shaders to use Shadertoy-style argument names.
> Shadertoy-style Shader Args

- docs/general_config.md
- source/App.cpp
- source/ConfigFiles.h
> Remove extra call to scene onSimulation()

- source/App.cpp
- source/App.h
- source/Weapon.cpp
- source/Weapon.h
Refactor the `Weapon` class code to better split it's functionalities from `App`/have it manage it's own projectiles/decals.
> Weapon Refactor

- source/App.cpp
- source/App.h
- source/ConfigFiles.h
This removes any (remaining) hard-coded 1920x1080 constants from the code in favor of using the `SystemConfig` to get the display resolution. Merging this pull request closes #91.
> Screen resolution adaptation

- docs/general_config.md
- docs/userConfigReadme.md
- source/App.cpp
- source/ConfigFiles.h
- source/GuiElements.cpp
This pull request handles 2 problems with the user settings save option:
1. It was not previously serialized to/from Any
2. It was drawn conditional on the `allowReticleChange` flag, which is incorrect
Merging this request closes #136.
> User save settings

- FirstPersonScience.sln
- FirstPersonScience.vcxproj
- FirstPersonScience.vcxproj.filters
This is a place to clean up/reorganize some VS solution/project file specific organization. Changes include:
-Selecting the `FirstPersonScience` project as the default startup project in the solution
- Adding the `Config Files` filter to the `FirstPersonScience` project
> Project reorganization

- source/Session.cpp
This corrects a regression where the app would crash if started with no valid sessions available for the user.
> Fix conditional ordering to prevent crash with no valid sessions

- source/GuiElements.cpp
This branch adds a fix for an exception that previously occurred when `showExperimentSettings = false` was added to the experiment config Any file.
Merging this PR closes #192.
> Quick fix for showExperimentSettings = false

- docs/startupConfigReadme.md
Forgot to add a sample in the docs in #195 . This pull request adds a sample.
> Updated sample startup config docs

- source/GuiElements.cpp
- source/GuiElements.h
This is a branch to address the issues with user menu controls (sliders and checkboxes) that was introduced in [this commit](
https://github.com/NVlabs/abstract-fps/commit/995d5d5bbe8f57b5f43084b572d2f0df3dcc23e2).
Merging this PR closes #208.
> Restore user menu slider and checkbox interaction

- source/FPSciApp.cpp
- source/Logger.cpp
This branch includes fixes for some small changes in the log files. These include:
* Different time zones (UTC vs local) being used in-log vs log filenames
* Miss events being logged twice per occurrence
Merging this PR closes #215.
> Fixes for some unexpected log behavior

- source/ConfigFiles.h
- source/Session.cpp
This pull request resets the weapon cooldown when starting a new trial.
> Cooldown reset

- docs/general_config.md
- source/Dialogs.h
- source/FPSciApp.cpp
This branch adds support for:
- A submit (and clear) button for multiple choice/rating dialogs
- Validation for empty text in text entry dialogs
Merging this PR closes #235.
> Additional dialog input validation

- source/FPSciApp.cpp
- source/GuiElements.cpp
- source/Session.cpp
This branch attempts to correct bugs around pointer vs camera control interaction of the mouse in various experiment configurations.
Merging this PR closes #230.
> Fixes for Pointer-based Interaction in the Dialog/Menu System

- docs/general_config.md
- source/FPSciApp.cpp
This branch supports multiline feedback strings via the `\n` character in provided feedback strings.
Merging this PR closes #240.
> Multiline Feedback Strings

- source/ConfigFiles.h
- source/FPSciApp.cpp
- source/FPSciApp.h
- source/GuiElements.cpp
- source/GuiElements.h
- source/Weapon.h
This branch fixes some problems with the `RenderControls` window including:
Merging this PR closes #241.
> Fixes for bugs in RenderControls window

- docs/general_config.md
- source/ConfigFiles.h
- source/Dialogs.h
- source/FPSciApp.cpp
- source/FPSciApp.h
Add support for key-bindings for question responses and fullscreen questions.
> Question Improvements

- source/FPSciApp.cpp
- source/Session.cpp
- source/WaypointManager.cpp
This branch attempts to reduce a memory leak that appears to be caused by creating new sessions within the application. It also includes general code cleanup that improves the consistency and readability of FPSciApp code.
> Fix(es) for memory leak(s) in new session logic

- docs/general_config.md
- source/ConfigFiles.h
- source/FPSciApp.cpp
- source/FPSciApp.h
- source/Logger.cpp
- source/Logger.h
- source/Session.cpp
- source/sqlHelpers.cpp
- source/sqlHelpers.h
Support a unified user/experiment results database for cleaner output.
> Support unified (per user) experiment results file

- docs/weaponConfigReadme.md
- source/ConfigFiles.h
- source/FPSciApp.cpp
- source/FPSciApp.h
- source/GuiElements.cpp
- source/Session.cpp
- source/Session.h
- source/Weapon.cpp
- source/Weapon.h
This branch makes the `Weapon` class more self-managing, and also adds support for a (visual only) weapon kick via the new `kickAngle` and `kickDuration` parameters.
> Weapon Improvement

- data-files/test/startupconfig.Any
Fixes a bug in running the tests left by #262
> Update test startupconfig to new style

- source/GuiElements.cpp
- source/GuiElements.h
This branch fixes an issue introduced in #274 wherein the "Resume" button in the user menu did not work as expected.
Merging this PR closes #282.
> Fix for broken user menu resume button

- docs/startupConfigReadme.md
- source/ExperimentConfig.cpp
- source/ExperimentConfig.h
- source/FPSciApp.cpp
- source/KeyMapping.cpp
- source/KeyMapping.h
- source/StartupConfig.cpp
- source/StartupConfig.h
- source/SystemConfig.cpp
- source/SystemConfig.h
- source/UserConfig.cpp
- source/UserConfig.h
- source/UserStatus.cpp
- source/UserStatus.h
- source/WaypointManager.cpp
- source/WaypointManager.h
This branch updates all FPSci Any outputs to be JSON compatible using the new 2nd argument of the `Any::save()` method.
Make sure to update and build G3D with `svn up` from the G3D install directory then `./buildg3d lib` from the `G3D10` directory within the install directory prior to building these changes.
Merging this PR closes #315
> Update Any output to be JSON compatible

- docs/general_config.md
- docs/resultsFiles.md
- source/Dialogs.h
- source/Logger.cpp
- source/Logger.h
- source/Session.cpp
This PR logs time, responses, response key bindings and the order randomization for questions per response.
> Log time, options and keys for questions

- docs/general_config.md
- docs/getting_started.md
This branch adds some documentation updates that don't fit within existing bug fixes/open pull requests.
> Documentation Updates

- source/FpsConfig.cpp
- source/FpsConfig.h
Questions are now serialized to Any, this is importantly primarily so that they are captured in/impact hashes appended to the results file.
> Questions to Any
